site_name: 快手小店 Python SDK
site_description: 快手小店开放平台Python SDK - 全功能异步客户端库
site_author: Kuaishou SDK Team
site_url: https://kwaixiaodian-python-sdk.readthedocs.io

repo_name: kuaishou/kwaixiaodian-python-sdk
repo_url: https://github.com/AndersonBY/kwaixiaodian-python-sdk
edit_uri: edit/main/docs/

theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

nav:
  - 首页: index.md
  - 快速开始: quickstart.md
  - 认证指南: authentication.md
  - 错误处理: error-handling.md
  - 最佳实践: best-practices.md
  - 示例代码: examples.md
  - API参考:
    - 概述: api-reference.md
    - 核心客户端: api/core-clients.md
    - 核心业务:
      - 订单服务: api/order-service.md
      - 商品服务: api/item-service.md
      - 售后服务: api/refund-service.md
      - 物流服务: api/logistics-service.md
      - 分销服务: api/distribution-service.md
      - 分销 · CPS 子服务: api/distribution-cps.md
      - 分销 · 投资活动子服务: api/distribution-investment.md
      - 分销 · 卖家活动子服务: api/distribution-seller.md
      - 分销 · 二级分销子服务: api/distribution-second.md
    - 财务管理:
      - 资金服务: api/funds-service.md
      - 发票服务: api/invoice-service.md
    - 店铺管理:
      - 店铺服务: api/shop-service.md
    - 基础模块: api/base-modules.md
  - 开发指南和规则协议:
    - 平台介绍:
      - 平台简介: 开发指南和规则协议/平台介绍/平台简介.md
      - 开放平台:
        - 开放平台入驻指南: 开发指南和规则协议/平台介绍/开放平台/开放平台入驻指南.md
        - 开放平台应用开发指南: 开发指南和规则协议/平台介绍/开放平台/开放平台应用开发指南.md
        - 开放平台开发者角色说明: 开发指南和规则协议/平台介绍/开放平台/开放平台开发者角色说明.md
      - 服务市场:
        - 服务市场入驻指南: 开发指南和规则协议/平台介绍/服务市场/服务市场入驻指南.md
    - 开发文档:
      - 新手指南: 开发指南和规则协议/开发文档/新手指南.md
      - SDK使用说明: 开发指南和规则协议/开发文档/SDK使用说明.md
      - API调用说明: 开发指南和规则协议/开发文档/API调用说明.md
      - API限流说明: 开发指南和规则协议/开发文档/API限流说明.md
      - APP授权说明: 开发指南和规则协议/开发文档/APP授权说明.md
      - 消息服务说明: 开发指南和规则协议/开发文档/消息服务说明.md
      - 物流公司编号: 开发指南和规则协议/开发文档/物流公司编号.md
      - 订单优惠信息子类型说明: 开发指南和规则协议/开发文档/订单优惠信息子类型说明.md
      - 返回码说明: 开发指南和规则协议/开发文档/返回码说明.md
      - 集成中心说明: 开发指南和规则协议/开发文档/集成中心说明.md
    - 规则协议:
      - 开放平台:
        - 应用流量申请规则: 开发指南和规则协议/规则协议/开放平台/应用流量申请规则.md
        - 开放平台安全开发规范: 开发指南和规则协议/规则协议/开放平台/开放平台安全开发规范.md
        - 开放平台日志接入规范: 开发指南和规则协议/规则协议/开放平台/开放平台日志接入规范.md
        - 快手电商开放平台开发者协议: 开发指南和规则协议/规则协议/开放平台/快手电商开放平台开发者协议.md
        - 快手电商开放平台运营规则: 开发指南和规则协议/规则协议/开放平台/快手电商开放平台运营规则.md
        - 快手电商开放平台隐私政策: 开发指南和规则协议/规则协议/开放平台/快手电商开放平台隐私政策.md
      - 服务市场:
        - 入驻类目资质及保证金要求: 开发指南和规则协议/规则协议/服务市场/入驻类目资质及保证金要求.md
        - 快手服务市场「货源市场」服务商准入及清退规则: 开发指南和规则协议/规则协议/服务市场/快手服务市场「货源市场」服务商准入及清退规则.md
        - 快手服务市场使用三方发品接口类服务商管理规范: 开发指南和规则协议/规则协议/服务市场/快手服务市场使用三方发品接口类服务商管理规范.md
        - 快手服务市场客服外包类目管理规范: 开发指南和规则协议/规则协议/服务市场/快手服务市场客服外包类目管理规范.md
        - 快手服务市场技术服务费收费规则: 开发指南和规则协议/规则协议/服务市场/快手服务市场技术服务费收费规则.md
        - 快手服务市场服务协议（服务商版）: 开发指南和规则协议/规则协议/服务市场/快手服务市场服务协议（服务商版）.md
        - 快手服务市场服务协议（用户版）: 开发指南和规则协议/规则协议/服务市场/快手服务市场服务协议（用户版）.md
        - 快手服务市场违规举报规则: 开发指南和规则协议/规则协议/服务市场/快手服务市场违规举报规则.md
        - 快手服务市场违规处罚规范: 开发指南和规则协议/规则协议/服务市场/快手服务市场违规处罚规范.md
        - 智能客服类目对接流程: 开发指南和规则协议/规则协议/服务市场/智能客服类目对接流程.md
        - 服务市场上架审核标准: 开发指南和规则协议/规则协议/服务市场/服务市场上架审核标准.md
        - 服务市场推荐资源位规则: 开发指南和规则协议/规则协议/服务市场/服务市场推荐资源位规则.md
        - 服务市场管理规范: 开发指南和规则协议/规则协议/服务市场/服务市场管理规范.md
        - 服务市场类目参考价要求: 开发指南和规则协议/规则协议/服务市场/服务市场类目参考价要求.md
      - 历史协议:
        - 开放平台开发者协议（已失效）: 开发指南和规则协议/规则协议/历史协议/开放平台开发者协议（已失效）.md
        - 快手服务市场服务协议（服务商版）（已失效）: 开发指南和规则协议/规则协议/历史协议/快手服务市场服务协议（服务商版）（已失效）.md
        - 快手服务市场服务协议（用户版）（已失效）: 开发指南和规则协议/规则协议/历史协议/快手服务市场服务协议（用户版）（已失效）.md
        - 快手电商商家授权服务协议（已失效）: 开发指南和规则协议/规则协议/历史协议/快手电商商家授权服务协议（已失效）.md
        - 快手电商商家服务市场服务协议（商家版）（已失效）: 开发指南和规则协议/规则协议/历史协议/快手电商商家服务市场服务协议（商家版）（已失效）.md
        - 快手电商商家服务市场服务协议（服务商版）（已失效）: 开发指南和规则协议/规则协议/历史协议/快手电商商家服务市场服务协议（服务商版）（已失效）.md
        - 快手电商开放平台开发者协议（已失效）: 开发指南和规则协议/规则协议/历史协议/快手电商开放平台开发者协议（已失效）.md
  - 开发者支持文档:
    - 开放平台:
      - 应用授权:
        - K0002 - 交易功能上线之后服务商如何进行上线前开发测试: 开发者支持文档/开放平台/应用授权/K0002 - 交易功能上线之后服务商如何进行上线前开发测试.md
        - K0003 - 调用API时报错 “token中无scope权限”: 开发者支持文档/开放平台/应用授权/K0003 - 调用API时报错 “token中无scope权限”.md
        - K0004 - 访问接口时返回“鉴权失败”是什么原因？: 开发者支持文档/开放平台/应用授权/K0004 - 访问接口时返回“鉴权失败”是什么原因？.md
        - K0005 - API接口返回 主账号不存在: 开发者支持文档/开放平台/应用授权/K0005 - API接口返回 主账号不存在.md
        - K0006 - 错误信息：AUTHORIZATION_REVOKED: 开发者支持文档/开放平台/应用授权/K0006 - 错误信息：AUTHORIZATION_REVOKED.md
        - K0007 - 授权无法识别用户昵称: 开发者支持文档/开放平台/应用授权/K0007 - 授权无法识别用户昵称.md
        - K0008 - 错误信息：refreshToken.discarded: 开发者支持文档/开放平台/应用授权/K0008 - 错误信息：refreshToken.discarded.md
        - K0009 - 报错 Invalid url: 开发者支持文档/开放平台/应用授权/K0009 - 报错 Invalid url.md
        - K0010 - 不属于此应用的授权用户或测试用户: 开发者支持文档/开放平台/应用授权/K0010 - 不属于此应用的授权用户或测试用户.md
        - K0011 - 用户如何扫码授权使用: 开发者支持文档/开放平台/应用授权/K0011 - 用户如何扫码授权使用.md
      - API调用:
        - K1001 - 当前库存不足，请减少预留库存: 开发者支持文档/开放平台/API调用/K1001 - 当前库存不足，请减少预留库存.md
        - K1002 - 仅支持在快手小店PC APP进行编辑: 开发者支持文档/开放平台/API调用/K1002 - 仅支持在快手小店PC APP进行编辑.md
        - K1003 - 添加商品接口报错：来源不可售卖: 开发者支持文档/开放平台/API调用/K1003 - 添加商品接口报错：来源不可售卖.md
        - K1004 - 访问接口时返回“验签失败”“签名校验失败”: 开发者支持文档/开放平台/API调用/K1004 - 访问接口时返回“验签失败”“签名校验失败”.md
        - K1005 - 接口报错：暂无站外分销推广权限: 开发者支持文档/开放平台/API调用/K1005 -接口报错：暂无站外分销推广权限.md
        - K1006 - order operation reject: 开发者支持文档/开放平台/API调用/K1006 - order operation reject.md
        - K1007 - 接口报错：品牌资质未关联: 开发者支持文档/开放平台/API调用/K1007 - 接口报错：品牌资质未关联.md
        - K1008 - API调用触发限流告警: 开发者支持文档/开放平台/API调用/K1008 - API调用触发限流告警.md
        - K1009 - 发货API拦截: 开发者支持文档/开放平台/API调用/K1009 - 发货API拦截.md
      - 业务咨询:
        - K6001 - 如何创建测试店铺: 开发者支持文档/开放平台/业务咨询/K6001 - 如何创建测试店铺.md
        - K6002 - 短信发送失败: 开发者支持文档/开放平台/业务咨询/K6002 - 短信发送失败.md
      - 应用管理:
        - K2001 - 安全扫描: 开发者支持文档/开放平台/应用管理/K2001 - 安全扫描.md
        - K2002 - 回调地址更新: 开发者支持文档/开放平台/应用管理/K2002 - 回调地址更新.md
        - K2003 - 如何提升应用评分: 开发者支持文档/开放平台/应用管理/K2003 - 如何提升应用评分.md
      - 数据安全:
        - K5001 - 订单数据导出: 开发者支持文档/开放平台/数据安全/K5001 - 订单数据导出.md
        - K5002 - 开发者如何验证应用已完成加密: 开发者支持文档/开放平台/数据安全/K5002- 开发者如何验证应用已完成加密.md
        - K5003 - 应用加密后商家如何发货: 开发者支持文档/开放平台/数据安全/K5003- 应用加密后商家如何发货.md
        - K5004 - 应用加密后商家如何获取明文: 开发者支持文档/开放平台/数据安全/K5004- 应用加密后商家如何获取明文.md
        - K5005 - 应用加密后商家解密为明文的规则: 开发者支持文档/开放平台/数据安全/K5005- 应用加密后商家解密为明文的规则.md
        - K5006 - 应用是否可以直接获取明文: 开发者支持文档/开放平台/数据安全/K5006- 应用是否可以直接获取明文.md
      - 消息推送:
        - K4001 - 消息未推送: 开发者支持文档/开放平台/消息推送/K4001 - 消息未推送.md
        - K4002 - 消息重复推送: 开发者支持文档/开放平台/消息推送/K4002 - 消息重复推送.md
        - K4003 - 推送url不可达: 开发者支持文档/开放平台/消息推送/K4003 - 推送url不可达.md
        - K4003 - 消息内容openId为空: 开发者支持文档/开放平台/消息推送/K4003 - 消息内容openId为空.md
        - K4004 - 消息推送接收失败是否会重试: 开发者支持文档/开放平台/消息推送/K4004 - 消息推送接收失败是否会重试.md
      - 账号管理:
        - K3001 - 开发者账号如何更换类型: 开发者支持文档/开放平台/账号管理/K3001 - 开发者账号如何更换类型.md
        - K3002 - 开发者账号登录和更换: 开发者支持文档/开放平台/账号管理/K3002 - 开发者账号登录和更换.md
        - K3003 - 开发者账号如何更改企业信息: 开发者支持文档/开放平台/账号管理/K3003 - 开发者账号如何更改企业信息.md
    - 服务市场:
      - 账号服务:
        - K7001 - 服务市场常见问题: 开发者支持文档/服务市场/账号服务/K7001-服务市场常见问题.md
        - K7003 - 开发者账号相关问题: 开发者支持文档/服务市场/账号服务/K7003-开发者账号相关问题.md
        - K7004 - 服务市场创建服务时AppKey列表空白: 开发者支持文档/服务市场/账号服务/K7004-服务市场创建服务时AppKey列表空白.md
        - K7006 - 快手服务商退出规范: 开发者支持文档/服务市场/账号服务/K7006-快手服务商退出规范.md
      - 服务交易:
        - K9001 - 上线交易模式常见问题（服务商侧）: 开发者支持文档/服务市场/服务交易/K9001-上线交易模式常见问题（服务商侧）.md
        - K9002 - 上线交易模式常见问题（商家侧）: 开发者支持文档/服务市场/服务交易/K9002-上线交易模式常见问题（商家侧）.md
        - K9003 - 快手服务市场技术服务费常见问题: 开发者支持文档/服务市场/服务交易/K9003-快手服务市场技术服务费常见问题.md
      - 保证金:
        - K8001 - 保证金常见问题: 开发者支持文档/服务市场/保证金/K8001-保证金常见问题.md
  - 更新日志: CHANGELOG.md

plugins:
  - search:
      lang: zh
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_signature_annotations: true
            show_root_heading: true
            show_root_toc_entry: true
            show_docstring_examples: true
            show_docstring_other_parameters: true
            signature_crossrefs: true
            merge_init_into_class: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AndersonBY/kwaixiaodian-python-sdk
    - icon: fontawesome/solid/paper-plane
      link: mailto:support@kwaixiaodian.com

extra_css:
  - stylesheets/extra.css
